# -*- coding: utf-8 -*-
"""FinMark_Data_Preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rPoIQjuwpwdlCY7Kp2O_gZTWRWqXKKSK
"""

import pandas as pd
import numpy as np

# Show all columns when we print a DataFrame (helps us see everything, nothing hidden)
pd.set_option('display.max_columns', None)

print("Libraries imported successfully.")

# File paths of the raw datasets
demo_path  = "customer_demographics_contaminated.csv"
trans_path = "customer_transactions_contaminated.csv"
social_path = "social_media_interactions_contaminated.csv"

# Load each dataset into its own DataFrame
df_demo   = pd.read_csv(demo_path)
df_trans  = pd.read_csv(trans_path)
df_social = pd.read_csv(social_path)

print("All three datasets loaded without errors.")

print("CUSTOMER DEMOGRAPHICS")
print("Shape:", df_demo.shape)
df_demo.head()

print("CUSTOMER TRANSACTIONS")
print("Shape:", df_trans.shape)
df_trans.head()

print("SOCIAL MEDIA INTERACTIONS")
print("Shape:", df_social.shape)
df_social.head()

print("--- Customer Demographics ---")
df_demo.info()

print("--- Customer Transactions ---")
df_trans.info()

print("--- Social Media Interactions ---")
df_social.info()

print("Duplicate rows in Customer Demographics:  ", df_demo.duplicated().sum())
print("Duplicate rows in Customer Transactions:   ", df_trans.duplicated().sum())
print("Duplicate rows in Social Media Interactions:", df_social.duplicated().sum())

# Let's look at a few duplicate examples so we understand what they look like
df_trans[df_trans.duplicated(keep=False)].sort_values('TransactionID').head(6)

print("Missing values - Customer Demographics")
print(df_demo.isnull().sum())
print()
print("Percentage missing:")
print((df_demo.isnull().mean() * 100).round(2).astype(str) + ' %')

print("Missing values - Customer Transactions")
print(df_trans.isnull().sum())
print()
print("Percentage missing:")
print((df_trans.isnull().mean() * 100).round(2).astype(str) + ' %')

print("Missing values - Social Media Interactions")
print(df_social.isnull().sum())
print()
print("Percentage missing:")
print((df_social.isnull().mean() * 100).round(2).astype(str) + ' %')

# Age should be numeric — let's see if any value cannot be converted to a number
non_numeric_ages = df_demo[pd.to_numeric(df_demo['Age'], errors='coerce').isna() & df_demo['Age'].notna()]
print("Non-numeric 'Age' values found:", non_numeric_ages['Age'].unique())

# Amount should be numeric — let's see if any value cannot be converted to a number
non_numeric_amount = df_trans[pd.to_numeric(df_trans['Amount'], errors='coerce').isna() & df_trans['Amount'].notna()]
print("Non-numeric 'Amount' values found:", non_numeric_amount['Amount'].unique())

# Also check for negative amounts, which don't make sense for a purchase
amount_numeric_preview = pd.to_numeric(df_trans['Amount'], errors='coerce')
print("Number of negative Amount values:", (amount_numeric_preview < 0).sum())

# Dates should all use the SAME format. Let's check if SignupDate mixes formats
# (e.g. 'YYYY-MM-DD' vs 'DD/MM/YYYY') by trying the standard ISO format on every value.
bad_dates_demo = df_demo[pd.to_datetime(df_demo['SignupDate'], format='%Y-%m-%d', errors='coerce').isna()]
print("Number of SignupDate values NOT in YYYY-MM-DD format:", len(bad_dates_demo))
print("Example of the inconsistent format found:", bad_dates_demo['SignupDate'].unique()[:5])

def parse_mixed_dates(date_series):
    """Convert a column of date-strings to real dates, even if it mixes
    'YYYY-MM-DD' and 'DD/MM/YYYY' formats."""
    def parse_one_value(value):
        if pd.isna(value):
            return pd.NaT
        try:
            return pd.to_datetime(value, format='%Y-%m-%d')
        except (ValueError, TypeError):
            pass
        try:
            return pd.to_datetime(value, format='%d/%m/%Y')
        except (ValueError, TypeError):
            return pd.NaT

    return date_series.apply(parse_one_value)

print("Helper function 'parse_mixed_dates' is ready to use.")

# Work on a copy so the original loaded data stays untouched for reference
demo_clean = df_demo.copy()

# Step 1: Replace the text 'Unknown' with an actual missing value, then convert to numeric
demo_clean['Age'] = demo_clean['Age'].replace('Unknown', np.nan)
demo_clean['Age'] = pd.to_numeric(demo_clean['Age'], errors='coerce')

# Step 2: Fill missing Age with the median age
median_age = demo_clean['Age'].median()
demo_clean['Age'] = demo_clean['Age'].fillna(median_age)
demo_clean['Age'] = demo_clean['Age'].astype(int)

print(f"Median age used to fill missing values: {median_age}")

# Step 3: Fill missing IncomeLevel with the label 'Unknown'
demo_clean['IncomeLevel'] = demo_clean['IncomeLevel'].fillna('Unknown')

# Step 4: Convert SignupDate to a real datetime type
demo_clean['SignupDate'] = parse_mixed_dates(demo_clean['SignupDate'])

# Step 5: Clean up text columns - remove extra spaces and keep consistent capitalization
for col in ['Gender', 'Location', 'IncomeLevel']:
    demo_clean[col] = demo_clean[col].str.strip().str.title()

print("Text cleaning and type conversion complete.")

# Step 6: Remove duplicate rows (keep the first occurrence of each)
before = demo_clean.shape[0]
demo_clean = demo_clean.drop_duplicates()
after = demo_clean.shape[0]
print(f"Removed {before - after} duplicate rows. Rows before: {before}, rows after: {after}")

# Step 7: Verify the cleaning worked
print("Missing values left:\n", demo_clean.isnull().sum())
print()
print("Duplicate rows left:", demo_clean.duplicated().sum())
print()
demo_clean.info()

demo_clean.head()

trans_clean = df_trans.copy()

# Step 1: Replace the text 'Free' with 0, then convert Amount to numeric
trans_clean['Amount'] = trans_clean['Amount'].replace('Free', 0)
trans_clean['Amount'] = pd.to_numeric(trans_clean['Amount'], errors='coerce')

# Step 2: Fill remaining missing Amounts with the median
median_amount = trans_clean['Amount'].median()
trans_clean['Amount'] = trans_clean['Amount'].fillna(median_amount)

print(f"Median amount used to fill missing values: {median_amount:.2f}")

# Step 3: Fix negative amounts by taking the absolute value
negative_count = (trans_clean['Amount'] < 0).sum()
trans_clean['Amount'] = trans_clean['Amount'].abs()
trans_clean['Amount'] = trans_clean['Amount'].round(2)

print(f"Fixed {negative_count} negative amount values by converting them to positive.")

# Step 4: Fill missing ProductCategory with 'Unknown'
trans_clean['ProductCategory'] = trans_clean['ProductCategory'].fillna('Unknown')

# Step 5: Convert TransactionDate to a real datetime type
trans_clean['TransactionDate'] = parse_mixed_dates(trans_clean['TransactionDate'])

print("Missing value fill and date conversion complete.")

# Step 6: Remove duplicate rows, then remove any leftover duplicate TransactionIDs (keep first)
before = trans_clean.shape[0]
trans_clean = trans_clean.drop_duplicates()
trans_clean = trans_clean.drop_duplicates(subset='TransactionID', keep='first')
after = trans_clean.shape[0]
print(f"Removed {before - after} duplicate rows. Rows before: {before}, rows after: {after}")

# Step 7: Verify the cleaning worked
print("Missing values left:\n", trans_clean.isnull().sum())
print()
print("Duplicate rows left:", trans_clean.duplicated().sum())
print("Duplicate TransactionIDs left:", trans_clean['TransactionID'].duplicated().sum())
print("Negative amounts left:", (trans_clean['Amount'] < 0).sum())
print()
trans_clean.info()

trans_clean.head()

social_clean = df_social.copy()

# Step 1 & 2: Fill missing categorical values
social_clean['Platform'] = social_clean['Platform'].fillna('Unknown')
social_clean['Sentiment'] = social_clean['Sentiment'].fillna('Not Specified')

# Step 3: Convert InteractionDate to a real datetime type
social_clean['InteractionDate'] = parse_mixed_dates(social_clean['InteractionDate'])

print("Missing value fill and date conversion complete.")

# Step 4: Remove duplicate rows, then remove any leftover duplicate InteractionIDs (keep first)
before = social_clean.shape[0]
social_clean = social_clean.drop_duplicates()
social_clean = social_clean.drop_duplicates(subset='InteractionID', keep='first')
after = social_clean.shape[0]
print(f"Removed {before - after} duplicate rows. Rows before: {before}, rows after: {after}")

# Step 5: Verify the cleaning worked
print("Missing values left:\n", social_clean.isnull().sum())
print()
print("Duplicate rows left:", social_clean.duplicated().sum())
print("Duplicate InteractionIDs left:", social_clean['InteractionID'].duplicated().sum())
print()
social_clean.info()

social_clean.head()

summary = pd.DataFrame({
    'Dataset': ['Customer Demographics', 'Customer Transactions', 'Social Media Interactions'],
    'Rows Before': [df_demo.shape[0], df_trans.shape[0], df_social.shape[0]],
    'Rows After': [demo_clean.shape[0], trans_clean.shape[0], social_clean.shape[0]],
    'Duplicates Before': [df_demo.duplicated().sum(), df_trans.duplicated().sum(), df_social.duplicated().sum()],
    'Duplicates After': [demo_clean.duplicated().sum(), trans_clean.duplicated().sum(), social_clean.duplicated().sum()],
    'Missing Values Before': [df_demo.isnull().sum().sum(), df_trans.isnull().sum().sum(), df_social.isnull().sum().sum()],
    'Missing Values After': [demo_clean.isnull().sum().sum(), trans_clean.isnull().sum().sum(), social_clean.isnull().sum().sum()],
})
summary

demo_clean.to_csv('customer_demographics_cleaned.csv', index=False)
trans_clean.to_csv('customer_transactions_cleaned.csv', index=False)
social_clean.to_csv('social_media_interactions_cleaned.csv', index=False)

print("Cleaned datasets saved successfully:")
print(" - customer_demographics_cleaned.csv")
print(" - customer_transactions_cleaned.csv")
print(" - social_media_interactions_cleaned.csv")