# -*- coding: utf-8 -*-
"""finmark_data_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11O03LO0ZTPipye5qpDQCiiSdrHaYIQE5
"""

import pandas as pd
import statistics as stats

import pandas as pd

# the 3 raw files FinMark gave us
df_demo = pd.read_csv("customer_demographics_contaminated.csv")
df_trans = pd.read_csv("customer_transactions_contaminated.csv")
df_social = pd.read_csv("social_media_interactions_contaminated.csv")

print(df_demo.shape, df_trans.shape, df_social.shape)

# dates are inconsistent - some rows are YYYY-MM-DD, others are DD/MM/YYYY
# this tries both formats one at a time instead of guessing
def parse_one_date(value):
    if pd.isna(value):
        return None
    try:
        return pd.to_datetime(value, format='%Y-%m-%d')
    except (ValueError, TypeError):
        pass
    try:
        return pd.to_datetime(value, format='%d/%m/%Y')
    except (ValueError, TypeError):
        return None

# removes exact duplicate rows by walking through the dataframe ourselves
# and keeping track of rows we've already seen
def remove_exact_duplicates(df):
    seen_rows = set()
    keep_indexes = []
    for i in range(len(df)):
        row_as_tuple = tuple(df.iloc[i])
        if row_as_tuple not in seen_rows:
            seen_rows.add(row_as_tuple)
            keep_indexes.append(i)
    return df.iloc[keep_indexes].reset_index(drop=True)

# removes rows that share the same ID (keeps the first one we run into)
def remove_duplicate_ids(df, id_column):
    seen_ids = set()
    keep_indexes = []
    for i in range(len(df)):
        current_id = df[id_column][i]
        if current_id not in seen_ids:
            seen_ids.add(current_id)
            keep_indexes.append(i)
    return df.iloc[keep_indexes].reset_index(drop=True)

import statistics as stats

# ---------- demographics ----------
demo_clean = df_demo.copy()

# Age: "Unknown" text, blanks, AND impossible ages (below 0 or above 100) all get treated as
# missing here, so we fix them at the source instead of just flagging them
cleaned_ages = []
for value in demo_clean['Age'].tolist():
    if pd.isna(value) or value == 'Unknown':
        cleaned_ages.append(None)
    else:
        age_number = int(float(value))
        if age_number < 0 or age_number > 100:
            cleaned_ages.append(None)  # impossible age, treat the same as missing
        else:
            cleaned_ages.append(age_number)

known_ages = [a for a in cleaned_ages if a is not None]
median_age = round(stats.median(known_ages))
demo_clean['Age'] = [a if a is not None else median_age for a in cleaned_ages]

print(f"Age values fixed (missing + 'Unknown' + impossible): {cleaned_ages.count(None)}")
print(f"Median age used to fill them in: {median_age}")

# IncomeLevel: blanks become their own "Unknown" category instead of a guess
demo_clean['IncomeLevel'] = ['Unknown' if pd.isna(v) else v for v in demo_clean['IncomeLevel'].tolist()]

# clean up spacing/casing on the text columns
for col in ['Gender', 'Location', 'IncomeLevel']:
    demo_clean[col] = [str(v).strip().title() for v in demo_clean[col].tolist()]

demo_clean['SignupDate'] = [parse_one_date(v) for v in demo_clean['SignupDate'].tolist()]

demo_clean = remove_exact_duplicates(demo_clean)

# the same CustomerID showing up more than once with different details each time.
# Keeping just the first record per customer fixes it
before_id_dedupe = len(demo_clean)
demo_clean = remove_duplicate_ids(demo_clean, 'CustomerID')
print(f"Removed {before_id_dedupe - len(demo_clean)} rows for repeated CustomerIDs")

print("Missing values left:", demo_clean.isnull().sum().sum())
print("Duplicate rows left:", demo_clean.duplicated().sum())
print("Any impossible ages left:", any(a < 0 or a > 100 for a in demo_clean['Age'].tolist()))
demo_clean.head()

# ---------- transactions ----------
trans_clean = df_trans.copy()

# Amount: "Free" becomes 0, blanks get filled in later with the median, and negative amounts
# get flipped positive right away since a purchase can't logically cost less than nothing
cleaned_amounts = []
for value in trans_clean['Amount'].tolist():
    if pd.isna(value):
        cleaned_amounts.append(None)
    elif value == 'Free':
        cleaned_amounts.append(0.0)
    else:
        cleaned_amounts.append(abs(float(value)))

known_amounts = [a for a in cleaned_amounts if a is not None]
median_amount = round(stats.median(known_amounts), 2)
trans_clean['Amount'] = [round(a, 2) if a is not None else median_amount for a in cleaned_amounts]

print(f"Median amount used to fill missing values: {median_amount}")

trans_clean['ProductCategory'] = ['Unknown' if pd.isna(v) else v for v in trans_clean['ProductCategory'].tolist()]
trans_clean['TransactionDate'] = [parse_one_date(v) for v in trans_clean['TransactionDate'].tolist()]

trans_clean = remove_exact_duplicates(trans_clean)
trans_clean = remove_duplicate_ids(trans_clean, 'TransactionID')

print("Missing values left:", trans_clean.isnull().sum().sum())
print("Duplicate rows left:", trans_clean.duplicated().sum())
print("Negative amounts left:", sum(1 for a in trans_clean['Amount'].tolist() if a < 0))
trans_clean.head()

# ---------- social media ----------
social_clean = df_social.copy()

social_clean['Platform'] = ['Unknown' if pd.isna(v) else v for v in social_clean['Platform'].tolist()]
# didn't want to default missing sentiment to "Neutral" since that's an actual sentiment value
social_clean['Sentiment'] = ['Not Specified' if pd.isna(v) else v for v in social_clean['Sentiment'].tolist()]
social_clean['InteractionDate'] = [parse_one_date(v) for v in social_clean['InteractionDate'].tolist()]

social_clean = remove_exact_duplicates(social_clean)
social_clean = remove_duplicate_ids(social_clean, 'InteractionID')

print("Missing values left:", social_clean.isnull().sum().sum())
print("Duplicate rows left:", social_clean.duplicated().sum())
social_clean.head()

# ---------- before/after summary for the report ----------
summary = pd.DataFrame({
    'Dataset': ['Demographics', 'Transactions', 'Social Media'],
    'Rows Before': [len(df_demo), len(df_trans), len(df_social)],
    'Rows After': [len(demo_clean), len(trans_clean), len(social_clean)],
    'Dupes Before': [df_demo.duplicated().sum(), df_trans.duplicated().sum(), df_social.duplicated().sum()],
    'Nulls Before': [df_demo.isnull().sum().sum(), df_trans.isnull().sum().sum(), df_social.isnull().sum().sum()],
})
summary

# export the final versions for github
demo_clean.to_csv('customer_demographics_cleaned.csv', index=False)
trans_clean.to_csv('customer_transactions_cleaned.csv', index=False)
social_clean.to_csv('social_media_interactions_cleaned.csv', index=False)

print("saved all 3 cleaned files")