# -*- coding: utf-8 -*-
"""FinMark_Milestone1_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10J72KzqEFtyHYZRIk7rk1Wanxt8awKU9

# FinMark Corporation — Milestone 1: ML Solution EDA

Exploratory data analysis on the cleaned FinMark datasets: checking distributions, computing descriptive stats, and flagging anything worth knowing before this data goes into modeling work.

We're keeping the analysis in plain Python so it's easier for us to follow and explain what each number actually means.

Datasets used:
- `customer_demographics_cleaned.csv`
- `customer_transactions_cleaned.csv`
- `social_media_interactions_cleaned.csv`
"""

import pandas as pd
import statistics as stats
import matplotlib.pyplot as plt
import random

plt.rcParams['figure.figsize'] = (7, 4)

"""## 1. Load the Cleaned Datasets"""

import pandas as pd
demo = pd.read_csv("customer_demographics_cleaned.csv")
trans = pd.read_csv("customer_transactions_cleaned.csv")
social = pd.read_csv("social_media_interactions_cleaned.csv")

print(len(demo), "demographics rows")
print(len(trans), "transaction rows")
print(len(social), "social media rows")
demo.head()

def count_values(column_list):
    counts = {}
    for val in column_list:
        counts[val] = counts.get(val, 0) + 1
    return counts

"""## 2. Customer Demographics

### 2.1 Descriptive statistics for `Age`
"""

import statistics as stats
ages = demo['Age'].tolist()

mean_age = stats.mean(ages)
median_age = stats.median(ages)
mode_age = stats.mode(ages)
min_age = min(ages)
max_age = max(ages)
range_age = max_age - min_age
std_age = stats.stdev(ages)
var_age = stats.variance(ages)

print("mean:", round(mean_age, 2))
print("median:", median_age)
print("mode:", mode_age)
print("min:", min_age)
print("max:", max_age)
print("range:", range_age)
print("std dev:", round(std_age, 2))
print("variance:", round(var_age, 2))

"""**Observation:** mean and median land close together (mid-40s), and min/max are a believable 18-70 — a normal, realistic-looking age range with no red flags."""

import matplotlib.pyplot as plt
plt.hist(ages, bins=20, edgecolor='black')
plt.title('Age Distribution (Customer Demographics)')
plt.xlabel('Age')
plt.ylabel('Number of Customers')
plt.show()

"""### 2.2 Quick sanity check on Age

Just double-checking nothing outside a normal human age range snuck in.
"""

invalid_ages = [a for a in ages if a < 0 or a > 100]
print("Rows with an impossible age (<0 or >100):", len(invalid_ages))

import random
# strip plot to see the individual spread - the color rule is kept in as a safety net,
# it would highlight anything that shouldn't be there in red
random.seed(42)
jitter_normal = [random.uniform(-0.3, 0.3) for _ in ages]

plt.figure(figsize=(7, 3.5))
colors = ['crimson' if (a < 0 or a > 100) else 'steelblue' for a in ages]
plt.scatter(ages, jitter_normal, c=colors, alpha=0.4, s=12)
plt.yticks([])
plt.title('Age Spread — Strip Plot')
plt.xlabel('Age')
plt.show()

"""**Observation:** zero impossible ages — every dot is blue, all sitting inside a realistic 18-70 range.

### 2.3 Duplicate customer check
"""

customer_ids = demo['CustomerID'].tolist()
id_counts = count_values(customer_ids)
repeated_ids = [cid for cid, count in id_counts.items() if count > 1]

print("Number of CustomerIDs that appear more than once:", len(repeated_ids))
print("Unique CustomerIDs:", len(id_counts), "out of", len(customer_ids), "rows")

"""**Observation:** every `CustomerID` is unique — no repeated or conflicting customer records.

### 2.4 Categorical frequency distributions — Gender, Income Level
"""

gender_counts = count_values(demo['Gender'].tolist())
income_counts = count_values(demo['IncomeLevel'].tolist())

print("Gender:", gender_counts)
print("Income Level:", income_counts)

fig, axes = plt.subplots(1, 2, figsize=(11, 4))

axes[0].bar(gender_counts.keys(), gender_counts.values(), color='steelblue', edgecolor='black')
axes[0].set_title('Gender Distribution')
axes[0].set_ylabel('Count')

axes[1].bar(income_counts.keys(), income_counts.values(), color='darkorange', edgecolor='black')
axes[1].set_title('Income Level Distribution')

plt.tight_layout()
plt.show()

"""**Observation:** Gender is close to a 50/50 split. Income Level is fairly even across High, Low, and Medium, with an `Unknown` bucket for rows that had no income data to begin with — balanced enough for modeling."""

locations = demo['Location'].tolist()
location_counts = count_values(locations)
unique_locations = len(location_counts)

print("Unique locations:", unique_locations, "out of", len(locations), "rows")

top_locations = sorted(location_counts.items(), key=lambda pair: pair[1], reverse=True)[:5]
for name, count in top_locations:
    print(name, "->", count)

"""**Observation:** `Location` is almost entirely unique values — most cities only show up once or twice, so as-is this column is too sparse to use as a normal category; it would need grouping into broader regions first.

## 3. Customer Transactions

### 3.1 Descriptive statistics for `Amount`
"""

amounts = trans['Amount'].tolist()

mean_amt = stats.mean(amounts)
median_amt = stats.median(amounts)
mode_amt = stats.mode(amounts)
min_amt = min(amounts)
max_amt = max(amounts)
range_amt = max_amt - min_amt
std_amt = stats.stdev(amounts)
var_amt = stats.variance(amounts)

print("mean:", round(mean_amt, 2))
print("median:", round(median_amt, 2))
print("mode:", mode_amt)
print("min:", min_amt)
print("max:", max_amt)
print("range:", round(range_amt, 2))
print("std dev:", round(std_amt, 2))
print("variance:", round(var_amt, 2))

"""**Observation:** mean (~489) and median (~492) are almost identical, and the standard deviation (~282) is fairly large relative to the mean — amounts are spread out widely and evenly, not clustered around one price point."""

plt.hist(amounts, bins=30, edgecolor='black', color='seagreen')
plt.title('Transaction Amount Distribution')
plt.xlabel('Amount')
plt.ylabel('Number of Transactions')
plt.show()

"""**Observation:** the histogram is basically flat/uniform from 0 to 1000, not the bell-curve shape you'd expect from real purchase amounts — this looks more like randomly generated numbers than real buying behavior. There's also a visible spike right around the median, which comes from filling originally-missing amounts with the median value during preprocessing, not a real spending pattern.

### 3.2 Checking for outliers using the IQR method
"""

sorted_amounts = sorted(amounts)
n = len(sorted_amounts)

q1 = sorted_amounts[n // 4]
q3 = sorted_amounts[(3 * n) // 4]
iqr = q3 - q1
lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr

outliers = [a for a in amounts if a < lower_bound or a > upper_bound]

print(f"Q1: {q1}  |  Q3: {q3}  |  IQR: {iqr}")
print(f"Lower bound: {lower_bound:.2f}  |  Upper bound: {upper_bound:.2f}")
print("Number of outlier transactions:", len(outliers))

"""**Observation:** no outliers by the standard IQR rule — lines up with the uniform-looking histogram, nothing statistically extreme in this column.

### 3.3 Categorical frequency distributions — Product Category, Payment Method
"""

category_counts = count_values(trans['ProductCategory'].tolist())
payment_counts = count_values(trans['PaymentMethod'].tolist())

print("Product Category:", category_counts)
print("Payment Method:", payment_counts)

fig, axes = plt.subplots(1, 2, figsize=(12, 4))

axes[0].bar(category_counts.keys(), category_counts.values(), color='mediumpurple', edgecolor='black')
axes[0].set_title('Product Category')
axes[0].set_ylabel('Count')
axes[0].tick_params(axis='x', rotation=45)

axes[1].bar(payment_counts.keys(), payment_counts.values(), color='indianred', edgecolor='black')
axes[1].set_title('Payment Method')

plt.tight_layout()
plt.show()

"""**Observation:** both columns are well balanced — no class imbalance issue for either one if they end up being used as features or targets.

### 3.4 Transactions over time
"""

trans_dates = trans['TransactionDate'].tolist()
years = [d[:4] for d in trans_dates]
year_counts = count_values(years)

for year in sorted(year_counts):
    print(year, "->", year_counts[year])

print()
print("Earliest date:", min(trans_dates))
print("Latest date:", max(trans_dates))

sorted_years = sorted(year_counts.keys())
plt.plot(sorted_years, [year_counts[y] for y in sorted_years], marker='o', color='teal')
plt.title('Transactions per Year')
plt.xlabel('Year')
plt.ylabel('Number of Transactions')
plt.ylim(0, max(year_counts.values()) * 1.15)
plt.show()

"""**Observation:** transactions span mid-2022 to mid-2024, with 2023 showing more activity than 2022 or 2024 — but those are both partial years in this data (it starts mid-2022 and cuts off mid-2024), so that's most likely why they look lower, not a real drop in activity.

## 4. Social Media Interactions

### 4.1 Frequency distributions — Platform, Interaction Type, Sentiment
"""

platform_counts = count_values(social['Platform'].tolist())
type_counts = count_values(social['InteractionType'].tolist())
sentiment_counts = count_values(social['Sentiment'].tolist())

print("Platform:", platform_counts)
print("Interaction Type:", type_counts)
print("Sentiment:", sentiment_counts)

fig, axes = plt.subplots(1, 3, figsize=(15, 4))

axes[0].bar(platform_counts.keys(), platform_counts.values(), color='cornflowerblue', edgecolor='black')
axes[0].set_title('Platform')

axes[1].bar(type_counts.keys(), type_counts.values(), color='goldenrod', edgecolor='black')
axes[1].set_title('Interaction Type')

axes[2].bar(sentiment_counts.keys(), sentiment_counts.values(), color='salmon', edgecolor='black')
axes[2].set_title('Sentiment')
axes[2].tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.show()

def label_if_big_enough(pct):
    return f'{pct:.1f}%' if pct > 3 else ''

fig, ax = plt.subplots(figsize=(7, 5))
wedges, _, _ = ax.pie(sentiment_counts.values(), autopct=label_if_big_enough, startangle=90, pctdistance=0.8)
ax.legend(wedges, sentiment_counts.keys(), title='Sentiment', loc='center left', bbox_to_anchor=(1, 0, 0.5, 1))
ax.set_title('Sentiment — Share of Total Interactions')
ax.axis('equal')
plt.tight_layout()
plt.show()

print("Exact share of the smallest categories:")
total = sum(sentiment_counts.values())
for label, count in sentiment_counts.items():
    share = count / total * 100
    if share <= 3:
        print(f"  {label}: {share:.1f}%  ({count} rows)")

"""**Observation — Platform & Interaction Type:** both are close to evenly split, no imbalance concern.

**Observation — Sentiment (this one's imbalanced):** `Positive`, `Neutral`, and `Negative` are fairly balanced against each other (~29-30% each), but `Very Negative` and `Very Positive` together only make up about 2% of the data. If Sentiment is ever used as a classification target, those two rare classes would need oversampling or class weighting since a model would barely see enough examples to learn them.

## 5. Relationships Between Variables

Since the three datasets share `CustomerID`, we connect them ourselves with a plain dictionary lookup and check whether things like age, gender, or income actually relate to spending behavior.
"""

customer_info = {}
for i in range(len(demo)):
    cid = demo['CustomerID'][i]
    customer_info[cid] = (demo['Age'][i], demo['Gender'][i], demo['IncomeLevel'][i])

matched_ages = []
matched_amounts = []
income_amounts = {}
gender_amounts = {}

for i in range(len(trans)):
    cid = trans['CustomerID'][i]
    amt = trans['Amount'][i]
    if cid in customer_info:
        age, gender, income = customer_info[cid]
        matched_ages.append(age)
        matched_amounts.append(amt)
        income_amounts.setdefault(income, []).append(amt)
        gender_amounts.setdefault(gender, []).append(amt)

print("Matched transactions to a customer record:", len(matched_ages))

"""### 5.1 Correlation between Age and Amount

We calculate Pearson correlation by hand using the standard formula.
"""

n = len(matched_ages)
mean_x = sum(matched_ages) / n
mean_y = sum(matched_amounts) / n

numerator = sum((matched_ages[i] - mean_x) * (matched_amounts[i] - mean_y) for i in range(n))
denominator_x = sum((x - mean_x) ** 2 for x in matched_ages) ** 0.5
denominator_y = sum((y - mean_y) ** 2 for y in matched_amounts) ** 0.5

correlation = numerator / (denominator_x * denominator_y)
print(f"Correlation between Age and Amount: {correlation:.4f}")

plt.scatter(matched_ages, matched_amounts, alpha=0.3, s=15, color='darkslateblue')
plt.title('Age vs. Transaction Amount')
plt.xlabel('Age')
plt.ylabel('Amount')
plt.show()

"""**Observation:** correlation is basically 0 — no relationship at all between a customer's age and how much they spend. The scatter plot backs this up: just a random cloud of points, no slope or pattern. The dense horizontal/vertical line running through the middle is the median-fill artifact from preprocessing, not a real customer pattern."""

print("Average Amount by Income Level:")
for income, amount_list in income_amounts.items():
    print(f"  {income}: {round(sum(amount_list)/len(amount_list), 2)}  (n={len(amount_list)})")

print()
print("Average Amount by Gender:")
for gender, amount_list in gender_amounts.items():
    print(f"  {gender}: {round(sum(amount_list)/len(amount_list), 2)}  (n={len(amount_list)})")

income_labels = list(income_amounts.keys())
income_data = [income_amounts[label] for label in income_labels]

fig, ax = plt.subplots()
ax.violinplot(income_data, showmeans=True, showmedians=True)
ax.set_xticks(range(1, len(income_labels) + 1))
ax.set_xticklabels(income_labels)
ax.set_title('Transaction Amount Spread by Income Level')
ax.set_ylabel('Amount')
plt.show()

"""**Observation:** average spending is almost identical across every Income Level and both genders, and the violin shapes are all the same wide, flat "barrel" — none of these groups spend meaningfully differently, in either amount or pattern. Combined with the flat/uniform histogram from section 3.1, this suggests the transaction amounts in this dataset don't carry a strong behavioral signal tied to who the customer is.

## 6. Summary — What This Means for Modeling

**Patterns / distributions**
- Age is centered in the mid-40s with a realistic 18-70 range.
- Transaction Amount is spread flat/uniformly across its whole range, not clustered like typical purchase behavior.
- Product Category, Payment Method, Platform, and Interaction Type are all close to evenly distributed.

**Balance / imbalance**
- Gender, Income Level, Product Category, Payment Method, Platform, and Interaction Type are all reasonably balanced — good for modeling.
- Sentiment is imbalanced: `Very Negative` and `Very Positive` together make up only about 2% of records, versus ~30% each for `Positive`, `Neutral`, and `Negative`.

**Outliers**
- No outliers detected in `Amount` using the IQR method.
- No impossible values or duplicate customer records remain in `Age`/`CustomerID`.

**Relationships**
- No meaningful correlation between Age and Amount, and no meaningful difference in average Amount across Income Level or Gender.
- `Location` is too sparse (mostly unique values) to be usable as-is; it would need grouping into broader regions.

**Recommendations before modeling**
- If Sentiment is used as a prediction target, account for the imbalance in `Very Negative` / `Very Positive`.
- Group `Location` into regions/countries if it's going to be used as a feature.
- Treat the lack of relationship between demographics and Amount as a sign this dataset may need enrichment (or may simply be synthetic/randomized) before it can support meaningful behavioral predictions.
"""